// <auto-generated />
using System;
using DazContentInstaller.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DazContentInstaller.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525011955_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("DazContentInstaller.Database.Archive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ArchiveSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AssetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetTypes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRoot")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentArchiveId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentArchiveId");

                    b.HasIndex("AssetLibraryId", "ArchiveName", "ParentArchiveId");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("DazContentInstaller.Database.AssetFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArchiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveRelativePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstalledRelativePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId", "ArchiveRelativePath")
                        .IsUnique();

                    b.ToTable("AssetFiles");
                });

            modelBuilder.Entity("DazContentInstaller.Database.AssetLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveBackupPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetLibraries");
                });

            modelBuilder.Entity("DazContentInstaller.Database.InstallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArchiveId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetFileId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBeenOverriden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstallRecordStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstalledFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetFileId")
                        .IsUnique();

                    b.HasIndex("InstalledFileId");

                    b.HasIndex("ArchiveId", "InstalledFileId", "HasBeenOverriden");

                    b.ToTable("InstallRecords");
                });

            modelBuilder.Entity("DazContentInstaller.Database.InstalledFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetLibraryId", "InstalledPath", "FileName")
                        .IsUnique();

                    b.ToTable("InstalledFiles");
                });

            modelBuilder.Entity("DazContentInstaller.Database.Archive", b =>
                {
                    b.HasOne("DazContentInstaller.Database.AssetLibrary", "AssetLibrary")
                        .WithMany("Archives")
                        .HasForeignKey("AssetLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DazContentInstaller.Database.Archive", "ParentArchive")
                        .WithMany("SubArchives")
                        .HasForeignKey("ParentArchiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AssetLibrary");

                    b.Navigation("ParentArchive");
                });

            modelBuilder.Entity("DazContentInstaller.Database.AssetFile", b =>
                {
                    b.HasOne("DazContentInstaller.Database.Archive", "Archive")
                        .WithMany("AssetFiles")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");
                });

            modelBuilder.Entity("DazContentInstaller.Database.InstallRecord", b =>
                {
                    b.HasOne("DazContentInstaller.Database.Archive", "Archive")
                        .WithMany()
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DazContentInstaller.Database.AssetFile", "AssetFile")
                        .WithOne("InstallRecord")
                        .HasForeignKey("DazContentInstaller.Database.InstallRecord", "AssetFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DazContentInstaller.Database.InstalledFile", "InstalledFile")
                        .WithMany("InstallRecords")
                        .HasForeignKey("InstalledFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");

                    b.Navigation("AssetFile");

                    b.Navigation("InstalledFile");
                });

            modelBuilder.Entity("DazContentInstaller.Database.InstalledFile", b =>
                {
                    b.HasOne("DazContentInstaller.Database.AssetLibrary", "AssetLibrary")
                        .WithMany("InstalledFiles")
                        .HasForeignKey("AssetLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetLibrary");
                });

            modelBuilder.Entity("DazContentInstaller.Database.Archive", b =>
                {
                    b.Navigation("AssetFiles");

                    b.Navigation("SubArchives");
                });

            modelBuilder.Entity("DazContentInstaller.Database.AssetFile", b =>
                {
                    b.Navigation("InstallRecord");
                });

            modelBuilder.Entity("DazContentInstaller.Database.AssetLibrary", b =>
                {
                    b.Navigation("Archives");

                    b.Navigation("InstalledFiles");
                });

            modelBuilder.Entity("DazContentInstaller.Database.InstalledFile", b =>
                {
                    b.Navigation("InstallRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
